name: task_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # Added this for AWS cognito set up earlier
    # Cognito SDK
  amazon_cognito_identity_dart_2: ^3.8.1
  # Secure storage for tokens
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
