name: task_tracker
description: "A Flutter project for tracking tasks with AWS Cognito auth and MongoDB storage"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.0

  # Database to store user created tasks
  mongo_dart: ^0.10.5

  # icons
  cupertino_icons: ^1.0.2

  # AWS Cognito
  amazon_cognito_identity_dart_2: ^3.8.1

  # Secure local storage (for tokens, etc.)
  flutter_secure_storage: ^8.0.0

  # Google Sign-In (optional)
  google_sign_in: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
